// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entry_Kind int32

const (
	Entry_QUOTE Entry_Kind = 0
	Entry_IMAGE Entry_Kind = 1
)

var Entry_Kind_name = map[int32]string{
	0: "QUOTE",
	1: "IMAGE",
}

var Entry_Kind_value = map[string]int32{
	"QUOTE": 0,
	"IMAGE": 1,
}

func (x Entry_Kind) String() string {
	return proto.EnumName(Entry_Kind_name, int32(x))
}

func (Entry_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{1, 0}
}

type Source struct {
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Titles               []string `protobuf:"bytes,4,rep,name=titles,proto3" json:"titles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{0}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *Source) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Source) GetTitles() []string {
	if m != nil {
		return m.Titles
	}
	return nil
}

type Entry struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind                 Entry_Kind           `protobuf:"varint,2,opt,name=kind,proto3,enum=service.Entry_Kind" json:"kind,omitempty"`
	Source               *Source              `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Titles               []string             `protobuf:"bytes,4,rep,name=titles,proto3" json:"titles,omitempty"`
	Files                []*File              `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	Description          string               `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Creators             []*Entity            `protobuf:"bytes,7,rep,name=creators,proto3" json:"creators,omitempty"`
	PublishedAt          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{1}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entry) GetKind() Entry_Kind {
	if m != nil {
		return m.Kind
	}
	return Entry_QUOTE
}

func (m *Entry) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Entry) GetTitles() []string {
	if m != nil {
		return m.Titles
	}
	return nil
}

func (m *Entry) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Entry) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Entry) GetCreators() []*Entity {
	if m != nil {
		return m.Creators
	}
	return nil
}

func (m *Entry) GetPublishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *Entry) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Entry) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("service.Entry_Kind", Entry_Kind_name, Entry_Kind_value)
	proto.RegisterType((*Source)(nil), "service.Source")
	proto.RegisterType((*Entry)(nil), "service.Entry")
}

func init() { proto.RegisterFile("entry.proto", fileDescriptor_daa6c5b6c627940f) }

var fileDescriptor_daa6c5b6c627940f = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xed, 0xba, 0x76, 0xf6, 0x75, 0x6e, 0x23, 0x82, 0x84, 0xe1, 0xa1, 0xcc, 0xc3, 0x0a,
	0x42, 0x0f, 0xf3, 0xe4, 0xc1, 0xc3, 0x0e, 0x55, 0x44, 0x44, 0x8c, 0xf3, 0xe4, 0x41, 0xb6, 0x26,
	0x9b, 0xc1, 0xae, 0x29, 0x49, 0x2a, 0xec, 0x3f, 0xf4, 0xcf, 0x92, 0xa6, 0xd9, 0x18, 0x8a, 0xec,
	0xf6, 0xfa, 0xbd, 0xef, 0xfb, 0xfa, 0xeb, 0x2b, 0x84, 0xac, 0xd0, 0x72, 0x93, 0x94, 0x52, 0x68,
	0x81, 0x3a, 0x8a, 0xc9, 0x2f, 0x9e, 0xb1, 0x61, 0x97, 0x15, 0x9a, 0x6b, 0x2b, 0x0f, 0xfb, 0x9a,
	0xaf, 0x99, 0xd2, 0xf3, 0x75, 0x69, 0x05, 0x58, 0xf2, 0x9c, 0x35, 0xf3, 0xe8, 0x0d, 0xfc, 0x17,
	0x51, 0xc9, 0x8c, 0xa1, 0x31, 0xf8, 0x4d, 0x0c, 0x3b, 0x91, 0x13, 0x87, 0x93, 0x7e, 0x62, 0xeb,
	0x92, 0xd4, 0xc8, 0xc4, 0xae, 0xd1, 0x00, 0xdc, 0x4a, 0xe6, 0xb8, 0x15, 0x39, 0x71, 0x40, 0xea,
	0x11, 0x9d, 0x81, 0xaf, 0xb9, 0xce, 0x99, 0xc2, 0xed, 0xc8, 0x8d, 0x03, 0x62, 0x9f, 0x46, 0xdf,
	0x2e, 0x78, 0x69, 0x0d, 0x88, 0x7a, 0xd0, 0xe2, 0xd4, 0x14, 0x07, 0xa4, 0xc5, 0x29, 0x1a, 0x43,
	0xfb, 0x93, 0x17, 0xd4, 0x94, 0xf4, 0x26, 0xa7, 0xfb, 0xaf, 0x92, 0x9b, 0xe4, 0x81, 0x17, 0x94,
	0x18, 0x43, 0x4d, 0xa5, 0x0c, 0x1f, 0x76, 0x7f, 0x51, 0x35, 0xd8, 0xc4, 0xae, 0xff, 0x63, 0x40,
	0x17, 0xe0, 0xd5, 0x9f, 0xab, 0xb0, 0x17, 0xb9, 0x71, 0x38, 0x39, 0xd9, 0xe5, 0x6f, 0x79, 0xce,
	0x48, 0xb3, 0x43, 0x11, 0x84, 0x94, 0xa9, 0x4c, 0xf2, 0x52, 0x73, 0x51, 0x60, 0xdf, 0x70, 0xee,
	0x4b, 0xe8, 0x12, 0x8e, 0x33, 0xc9, 0xe6, 0x5a, 0x48, 0x85, 0x3b, 0xa6, 0xe9, 0xcf, 0x7d, 0x76,
	0x06, 0x74, 0x03, 0xdd, 0xb2, 0x5a, 0xe4, 0x5c, 0x7d, 0x30, 0xfa, 0x3e, 0xd7, 0x38, 0x30, 0xe8,
	0xc3, 0x64, 0x25, 0xc4, 0x6a, 0x7b, 0xf9, 0x45, 0xb5, 0x4c, 0x66, 0xdb, 0x1f, 0x43, 0xc2, 0x9d,
	0x7f, 0xaa, 0xd1, 0x35, 0x80, 0xa9, 0x6a, 0xc2, 0x70, 0x30, 0x1c, 0x58, 0x77, 0x13, 0xad, 0x4a,
	0xba, 0x8d, 0x86, 0x87, 0xa3, 0xd6, 0x3d, 0xd5, 0xa3, 0x73, 0x68, 0xd7, 0x77, 0x47, 0x01, 0x78,
	0xcf, 0xaf, 0x4f, 0xb3, 0x74, 0x70, 0x54, 0x8f, 0xf7, 0x8f, 0xd3, 0xbb, 0x74, 0xe0, 0x2c, 0x7c,
	0x13, 0xbe, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xba, 0x86, 0xc2, 0x71, 0x02, 0x00, 0x00,
}
