swagger: '2.0'
info:
  version: 0.1.0
  title: Magdas API Docs
  description: >-
    This is a the API docs for magda
securityDefinitions:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT  
security:
  - bearerAuth: []
consumes:
  - application/json
produces:
  - application/json
schemes:
  - https
responses:
  error:
    description: error
    schema:
      $ref: '#/definitions/error'
host: api.netlify.com
basePath: /api/v1
paths:
  /entries:
    post:
      operationId: createEntry
      consumes:
        - application/json
      parameters:
        - name: entry
          in: body
          schema:
            $ref: '#/definitions/entry'
          required: true
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/entry'
        default:
          $ref: '#/responses/error'
  /entries/{entry_id}:
    parameters:
      - name: entry_id
        type: string
        in: path
        required: true
    get:
      operationId: getEntry
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/entry'
        default:
          $ref: '#/responses/error'
definitions:
  entry:
    type: object
    properties:
      id:
        type: string
      kind:
        type: string
        enum:
          - quote
          - image
      source:
        $ref: '#/definitions/source'
      titles:
        type: array
        items:
          type: string
      files:
        type: array
        items:
          $ref: '#/definitions/file'
      description:
        type: string
      creators:
        type: array
        items:
          $ref: '#/definitions/entity'
      published_at:
        type: string
        format: dateTime
      created_at:
        type: string
        format: dateTime
      updated_at:
        type: string
        format: dateTime
  source:
    type: object
    properties:
      entity:
        $ref: '#/definitions/entity'
      url:
        type: string
      titles:
        type: array
        items:
          type: string
  file:
    type: object
    properties:
      path:
        type: string
      source_url:
        type: string
      content_type:
        type: string
      filename:
        type: string
      width:
        type: integer
      height:
        type: integer
      created_at:
        type: string
        format: dateTime
      updated_at:
        type: string
        format: dateTime
  entity:
    type: object
    properties:
      id:
        type: string
      kind:
        type: string
        enum:
          - person
          - organization
      names:
        type: array
        items:
          type: string
      urls:
        type: array
        items:
          type: string  
      description:
        type: string  
      created_at:
        type: string
        format: dateTime
      updated_at:
        type: string
        format: dateTime
      files:
        type: array
        items:
          $ref: '#/definitions/file'
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
        x-nullable: false