// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

package magda

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entity_Kind int32

const (
	Entity_PERSON       Entity_Kind = 0
	Entity_ORGANIZATION Entity_Kind = 1
)

var Entity_Kind_name = map[int32]string{
	0: "PERSON",
	1: "ORGANIZATION",
}

var Entity_Kind_value = map[string]int32{
	"PERSON":       0,
	"ORGANIZATION": 1,
}

func (x Entity_Kind) String() string {
	return proto.EnumName(Entity_Kind_name, int32(x))
}

func (Entity_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0, 0}
}

type Entity struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind                 Entity_Kind          `protobuf:"varint,2,opt,name=kind,proto3,enum=magda.Entity_Kind" json:"kind,omitempty"`
	Names                []string             `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty"`
	Urls                 []string             `protobuf:"bytes,4,rep,name=urls,proto3" json:"urls,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Files                []*File              `protobuf:"bytes,8,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entity) GetKind() Entity_Kind {
	if m != nil {
		return m.Kind
	}
	return Entity_PERSON
}

func (m *Entity) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Entity) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *Entity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Entity) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Entity) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Entity) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterEnum("magda.Entity_Kind", Entity_Kind_name, Entity_Kind_value)
	proto.RegisterType((*Entity)(nil), "magda.Entity")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor_cf50d946d740d100) }

var fileDescriptor_cf50d946d740d100 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0xbf, 0xa4, 0x49, 0x3e, 0x7a, 0x53, 0x95, 0xea, 0x8a, 0xc1, 0xea, 0x64, 0x2a, 0x84,
	0x32, 0x79, 0x08, 0x13, 0x63, 0x86, 0x82, 0x2a, 0xa4, 0x04, 0x99, 0x4e, 0x2c, 0xc8, 0xad, 0xdd,
	0xc8, 0x22, 0xff, 0x94, 0x38, 0x03, 0xcf, 0xc8, 0x4b, 0xa1, 0x38, 0x89, 0xc4, 0xc6, 0x76, 0x7d,
	0xee, 0xf9, 0xf9, 0xf8, 0x18, 0x56, 0xaa, 0x32, 0xda, 0x7c, 0xb1, 0xa6, 0xad, 0x4d, 0x8d, 0x7e,
	0x29, 0x72, 0x29, 0xb6, 0xd7, 0x46, 0x97, 0xaa, 0x33, 0xa2, 0x6c, 0x46, 0x7d, 0x0b, 0x17, 0x5d,
	0xa8, 0x71, 0xde, 0x7d, 0xbb, 0x10, 0xec, 0x2d, 0x84, 0x6b, 0x70, 0xb5, 0x24, 0x0e, 0x75, 0xa2,
	0x25, 0x77, 0xb5, 0xc4, 0x7b, 0xf0, 0x3e, 0x75, 0x25, 0x89, 0x4b, 0x9d, 0x68, 0x1d, 0x23, 0xb3,
	0xb7, 0xb1, 0xd1, 0xcc, 0x5e, 0x74, 0x25, 0xb9, 0xdd, 0xe3, 0x0d, 0xf8, 0x95, 0x28, 0x55, 0x47,
	0x16, 0x74, 0x11, 0x2d, 0xf9, 0x78, 0x40, 0x04, 0xaf, 0x6f, 0x8b, 0x8e, 0x78, 0x56, 0xb4, 0x33,
	0x52, 0x08, 0xa5, 0xea, 0xce, 0xad, 0x6e, 0x8c, 0xae, 0x2b, 0xe2, 0xdb, 0xa8, 0xdf, 0x12, 0x3e,
	0x02, 0x9c, 0x5b, 0x25, 0x8c, 0x92, 0x1f, 0xc2, 0x90, 0x80, 0x3a, 0x51, 0x18, 0x6f, 0x59, 0x5e,
	0xd7, 0xf9, 0xfc, 0xe2, 0x53, 0x7f, 0x61, 0xc7, 0xb9, 0x10, 0x5f, 0x4e, 0xee, 0xc4, 0x0c, 0x68,
	0xdf, 0xc8, 0x19, 0xfd, 0xff, 0x37, 0x3a, 0xb9, 0x13, 0x83, 0xb7, 0xe0, 0x0f, 0x5f, 0xd2, 0x91,
	0x2b, 0xba, 0x88, 0xc2, 0x38, 0x9c, 0xaa, 0x3e, 0xe9, 0x42, 0xf1, 0x71, 0xb3, 0xbb, 0x03, 0x6f,
	0xa8, 0x8c, 0x00, 0xc1, 0xeb, 0x9e, 0xbf, 0x65, 0xe9, 0xe6, 0x1f, 0x6e, 0x60, 0x95, 0xf1, 0xe7,
	0x24, 0x3d, 0xbc, 0x27, 0xc7, 0x43, 0x96, 0x6e, 0x9c, 0x53, 0x60, 0x73, 0x1e, 0x7e, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x66, 0x93, 0xdc, 0xd3, 0x88, 0x01, 0x00, 0x00,
}
