// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package magda

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Path                 string               `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SourceUrl            string               `protobuf:"bytes,2,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	ContentType          string               `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Filename             string               `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	Width                int64                `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Hieght               int64                `protobuf:"varint,6,opt,name=hieght,proto3" json:"hieght,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetSourceUrl() string {
	if m != nil {
		return m.SourceUrl
	}
	return ""
}

func (m *File) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *File) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *File) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *File) GetHieght() int64 {
	if m != nil {
		return m.Hieght
	}
	return 0
}

func (m *File) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *File) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "magda.File")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0x41, 0x6b, 0x83, 0x40,
	0x10, 0x85, 0x31, 0x51, 0x1b, 0x27, 0x85, 0xc2, 0x50, 0xca, 0x22, 0x14, 0x6c, 0x4f, 0x9e, 0x3c,
	0xb4, 0xa7, 0x1e, 0x73, 0xe9, 0x0f, 0x90, 0xf4, 0x2c, 0x1b, 0x9d, 0xe8, 0x82, 0xba, 0xcb, 0x66,
	0x96, 0x92, 0xff, 0xd2, 0x1f, 0x5b, 0xba, 0xae, 0xbd, 0xe6, 0x36, 0xef, 0x7b, 0xef, 0xc1, 0x3c,
	0x80, 0xb3, 0x1a, 0xa9, 0x32, 0x56, 0xb3, 0xc6, 0x64, 0x92, 0x7d, 0x27, 0xf3, 0x07, 0x56, 0x13,
	0x5d, 0x58, 0x4e, 0x66, 0xe1, 0xaf, 0x3f, 0x1b, 0x88, 0x3f, 0xd5, 0x48, 0x88, 0x10, 0x1b, 0xc9,
	0x83, 0x88, 0x8a, 0xa8, 0xcc, 0x6a, 0x7f, 0xe3, 0x33, 0xc0, 0x45, 0x3b, 0xdb, 0x52, 0xe3, 0xec,
	0x28, 0x36, 0xde, 0xc9, 0x16, 0xf2, 0x65, 0x47, 0x7c, 0x81, 0xfb, 0x56, 0xcf, 0x4c, 0x33, 0x37,
	0x7c, 0x35, 0x24, 0xb6, 0x3e, 0xb0, 0x0f, 0xec, 0x78, 0x35, 0x84, 0x39, 0xec, 0xfe, 0x9e, 0x98,
	0xe5, 0x44, 0x22, 0xf6, 0xf6, 0xbf, 0xc6, 0x47, 0x48, 0xbe, 0x55, 0xc7, 0x83, 0x48, 0x8a, 0xa8,
	0xdc, 0xd6, 0x8b, 0xc0, 0x27, 0x48, 0x07, 0x45, 0xfd, 0xc0, 0x22, 0xf5, 0x38, 0x28, 0xfc, 0x00,
	0x68, 0x2d, 0x49, 0xa6, 0xae, 0x91, 0x2c, 0xee, 0x8a, 0xa8, 0xdc, 0xbf, 0xe5, 0x55, 0xaf, 0x75,
	0xbf, 0x6e, 0x3c, 0xb9, 0x73, 0x75, 0x5c, 0xe7, 0xd5, 0x59, 0x48, 0x1f, 0x7c, 0xd5, 0x99, 0x6e,
	0xad, 0xee, 0x6e, 0x57, 0x43, 0xfa, 0xc0, 0xa7, 0xd4, 0xdb, 0xef, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x1f, 0x5e, 0x05, 0xac, 0x4b, 0x01, 0x00, 0x00,
}
