// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Entry interface {
	IsEntry()
}

// A file is a blob of bytes.
type File interface {
	IsFile()
}

type Dimensions struct {
	Width  *int `json:"width"`
	Height *int `json:"height"`
}

// An entity represents an Active thing ie a  person or organization.
type Entity struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Websites    []*Website `json:"websites"`
	Images      []*Image   `json:"images"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}

// An image is a file that you can display to a user.
type Image struct {
	ID string `json:"id"`
	// A URL where the user can download the bytes from. These URLs are timesensitve.
	URL string `json:"url"`
	// The content type of the bytes
	ContentType string `json:"contentType"`
	// A suggested name for this blob of bytes on disk.
	FileName   *string     `json:"fileName"`
	CreatedOn  time.Time   `json:"createdOn"`
	Dimensions *Dimensions `json:"dimensions"`
}

func (Image) IsFile() {}

type ImageEntry struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Image       *Image    `json:"image"`
	Source      *Source   `json:"source"`
	Creators    []*Entity `json:"creators"`
}

func (ImageEntry) IsEntry() {}

type Source struct {
	Page   *Website `json:"page"`
	Site   *Website `json:"site"`
	Entity *Entity  `json:"entity"`
}

// A source file is something that was, or will be, copied into the system. It's used to document provenance.
//
// It has one property which is a url which should be a URL the user can use to download the bytes from. The URLs are time sensitve.
type SourceFile struct {
	ID string `json:"id"`
	// url is a link to a canonical file
	URL string `json:"url"`
	// content_type is a guess at the files content_type
	ContentType string `json:"contentType"`
}

type TextEntry struct {
	ID       string    `json:"id"`
	Text     string    `json:"text"`
	Image    *Image    `json:"image"`
	Source   *Source   `json:"source"`
	Creators []*Entity `json:"creators"`
}

func (TextEntry) IsEntry() {}

type WebsiteInput struct {
	URL         string      `json:"url"`
	Kind        WebsiteKind `json:"kind"`
	Title       *string     `json:"title"`
	Description *string     `json:"description"`
}

type WebsiteSearch struct {
	ID  *string `json:"id"`
	URL *string `json:"url"`
}
