// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateEntryCreatedCode is the HTTP code returned for type CreateEntryCreated
const CreateEntryCreatedCode int = 201

/*CreateEntryCreated Created

swagger:response createEntryCreated
*/
type CreateEntryCreated struct {

	/*
	  In: Body
	*/
	Payload *CreateEntryCreatedBody `json:"body,omitempty"`
}

// NewCreateEntryCreated creates CreateEntryCreated with default headers values
func NewCreateEntryCreated() *CreateEntryCreated {

	return &CreateEntryCreated{}
}

// WithPayload adds the payload to the create entry created response
func (o *CreateEntryCreated) WithPayload(payload *CreateEntryCreatedBody) *CreateEntryCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create entry created response
func (o *CreateEntryCreated) SetPayload(payload *CreateEntryCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateEntryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateEntryDefault error

swagger:response createEntryDefault
*/
type CreateEntryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *CreateEntryDefaultBody `json:"body,omitempty"`
}

// NewCreateEntryDefault creates CreateEntryDefault with default headers values
func NewCreateEntryDefault(code int) *CreateEntryDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateEntryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create entry default response
func (o *CreateEntryDefault) WithStatusCode(code int) *CreateEntryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create entry default response
func (o *CreateEntryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create entry default response
func (o *CreateEntryDefault) WithPayload(payload *CreateEntryDefaultBody) *CreateEntryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create entry default response
func (o *CreateEntryDefault) SetPayload(payload *CreateEntryDefaultBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateEntryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
