// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEntryParams creates a new GetEntryParams object
// no default values defined in spec.
func NewGetEntryParams() GetEntryParams {

	return GetEntryParams{}
}

// GetEntryParams contains all the bound params for the get entry operation
// typically these are obtained from a http.Request
//
// swagger:parameters getEntry
type GetEntryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	EntryID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetEntryParams() beforehand.
func (o *GetEntryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rEntryID, rhkEntryID, _ := route.Params.GetOK("entry_id")
	if err := o.bindEntryID(rEntryID, rhkEntryID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEntryID binds and validates parameter EntryID from path.
func (o *GetEntryParams) bindEntryID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.EntryID = raw

	return nil
}
