// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Magdas API Docs
//
//  This is a the API docs for magda
//  Schemes:
//    https
//  Host: api.netlify.com
//  BasePath: /api/v1
//  Version: 0.1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
