// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a the API docs for magda",
    "title": "Magdas API Docs",
    "version": "0.1.0"
  },
  "host": "api.netlify.com",
  "basePath": "/api/v1",
  "paths": {
    "/entries": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "operationId": "createEntry",
        "parameters": [
          {
            "name": "entry",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/entry"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/entry"
            }
          },
          "default": {
            "$ref": "#/responses/error"
          }
        }
      }
    },
    "/entries/{entry_id}": {
      "get": {
        "operationId": "getEntry",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/entry"
            }
          },
          "default": {
            "$ref": "#/responses/error"
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "entry_id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "entity": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "description": {
          "type": "string"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/file"
          }
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "person",
            "organization"
          ]
        },
        "names": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "entry": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "creators": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/entity"
          }
        },
        "description": {
          "type": "string"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/file"
          }
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "quote",
            "image"
          ]
        },
        "published_at": {
          "type": "string",
          "format": "dateTime"
        },
        "source": {
          "$ref": "#/definitions/source"
        },
        "titles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string",
          "x-nullable": false
        }
      }
    },
    "file": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "source": {
      "type": "object",
      "properties": {
        "entity": {
          "$ref": "#/definitions/entity"
        },
        "titles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "url": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "error": {
      "description": "error",
      "schema": {
        "$ref": "#/definitions/error"
      }
    }
  },
  "securityDefinitions": {
    "netlifyAuth": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://app.netlify.com/authorize"
    }
  },
  "security": [
    {
      "netlifyAuth": []
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a the API docs for magda",
    "title": "Magdas API Docs",
    "version": "0.1.0"
  },
  "host": "api.netlify.com",
  "basePath": "/api/v1",
  "paths": {
    "/entries": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "operationId": "createEntry",
        "parameters": [
          {
            "name": "entry",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "created_at": {
                  "type": "string",
                  "format": "dateTime"
                },
                "creators": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/CreatorsItems0"
                  }
                },
                "description": {
                  "type": "string"
                },
                "files": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/FilesItems0"
                  }
                },
                "id": {
                  "type": "string"
                },
                "kind": {
                  "type": "string",
                  "enum": [
                    "quote",
                    "image"
                  ]
                },
                "published_at": {
                  "type": "string",
                  "format": "dateTime"
                },
                "source": {
                  "type": "object",
                  "properties": {
                    "entity": {
                      "type": "object",
                      "properties": {
                        "created_at": {
                          "type": "string",
                          "format": "dateTime"
                        },
                        "description": {
                          "type": "string"
                        },
                        "files": {
                          "type": "array",
                          "items": {
                            "$ref": "#/definitions/CreateEntryParamsBodySourceEntityFilesItems0"
                          }
                        },
                        "id": {
                          "type": "string"
                        },
                        "kind": {
                          "type": "string",
                          "enum": [
                            "person",
                            "organization"
                          ]
                        },
                        "names": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "updated_at": {
                          "type": "string",
                          "format": "dateTime"
                        },
                        "urls": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "titles": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "url": {
                      "type": "string"
                    }
                  }
                },
                "titles": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "updated_at": {
                  "type": "string",
                  "format": "dateTime"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "type": "object",
              "properties": {
                "created_at": {
                  "type": "string",
                  "format": "dateTime"
                },
                "creators": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/CreatorsItems0"
                  }
                },
                "description": {
                  "type": "string"
                },
                "files": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/FilesItems0"
                  }
                },
                "id": {
                  "type": "string"
                },
                "kind": {
                  "type": "string",
                  "enum": [
                    "quote",
                    "image"
                  ]
                },
                "published_at": {
                  "type": "string",
                  "format": "dateTime"
                },
                "source": {
                  "type": "object",
                  "properties": {
                    "entity": {
                      "type": "object",
                      "properties": {
                        "created_at": {
                          "type": "string",
                          "format": "dateTime"
                        },
                        "description": {
                          "type": "string"
                        },
                        "files": {
                          "type": "array",
                          "items": {
                            "$ref": "#/definitions/CreateEntryCreatedBodySourceEntityFilesItems0"
                          }
                        },
                        "id": {
                          "type": "string"
                        },
                        "kind": {
                          "type": "string",
                          "enum": [
                            "person",
                            "organization"
                          ]
                        },
                        "names": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "updated_at": {
                          "type": "string",
                          "format": "dateTime"
                        },
                        "urls": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "titles": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "url": {
                      "type": "string"
                    }
                  }
                },
                "titles": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "updated_at": {
                  "type": "string",
                  "format": "dateTime"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "type": "object",
              "required": [
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "message": {
                  "type": "string",
                  "x-nullable": false
                }
              }
            }
          }
        }
      }
    },
    "/entries/{entry_id}": {
      "get": {
        "operationId": "getEntry",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "created_at": {
                  "type": "string",
                  "format": "dateTime"
                },
                "creators": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/CreatorsItems0"
                  }
                },
                "description": {
                  "type": "string"
                },
                "files": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/FilesItems0"
                  }
                },
                "id": {
                  "type": "string"
                },
                "kind": {
                  "type": "string",
                  "enum": [
                    "quote",
                    "image"
                  ]
                },
                "published_at": {
                  "type": "string",
                  "format": "dateTime"
                },
                "source": {
                  "type": "object",
                  "properties": {
                    "entity": {
                      "type": "object",
                      "properties": {
                        "created_at": {
                          "type": "string",
                          "format": "dateTime"
                        },
                        "description": {
                          "type": "string"
                        },
                        "files": {
                          "type": "array",
                          "items": {
                            "$ref": "#/definitions/GetEntryOKBodySourceEntityFilesItems0"
                          }
                        },
                        "id": {
                          "type": "string"
                        },
                        "kind": {
                          "type": "string",
                          "enum": [
                            "person",
                            "organization"
                          ]
                        },
                        "names": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "updated_at": {
                          "type": "string",
                          "format": "dateTime"
                        },
                        "urls": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "titles": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "url": {
                      "type": "string"
                    }
                  }
                },
                "titles": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "updated_at": {
                  "type": "string",
                  "format": "dateTime"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "type": "object",
              "required": [
                "message"
              ],
              "properties": {
                "code": {
                  "type": "integer",
                  "format": "int64"
                },
                "message": {
                  "type": "string",
                  "x-nullable": false
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "entry_id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "CreateEntryCreatedBodySource": {
      "type": "object",
      "properties": {
        "entity": {
          "type": "object",
          "properties": {
            "created_at": {
              "type": "string",
              "format": "dateTime"
            },
            "description": {
              "type": "string"
            },
            "files": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CreateEntryCreatedBodySourceEntityFilesItems0"
              }
            },
            "id": {
              "type": "string"
            },
            "kind": {
              "type": "string",
              "enum": [
                "person",
                "organization"
              ]
            },
            "names": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "updated_at": {
              "type": "string",
              "format": "dateTime"
            },
            "urls": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "titles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "url": {
          "type": "string"
        }
      }
    },
    "CreateEntryCreatedBodySourceEntity": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "description": {
          "type": "string"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CreateEntryCreatedBodySourceEntityFilesItems0"
          }
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "person",
            "organization"
          ]
        },
        "names": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "CreateEntryCreatedBodySourceEntityFilesItems0": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "CreateEntryParamsBodySource": {
      "type": "object",
      "properties": {
        "entity": {
          "type": "object",
          "properties": {
            "created_at": {
              "type": "string",
              "format": "dateTime"
            },
            "description": {
              "type": "string"
            },
            "files": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CreateEntryParamsBodySourceEntityFilesItems0"
              }
            },
            "id": {
              "type": "string"
            },
            "kind": {
              "type": "string",
              "enum": [
                "person",
                "organization"
              ]
            },
            "names": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "updated_at": {
              "type": "string",
              "format": "dateTime"
            },
            "urls": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "titles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "url": {
          "type": "string"
        }
      }
    },
    "CreateEntryParamsBodySourceEntity": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "description": {
          "type": "string"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CreateEntryParamsBodySourceEntityFilesItems0"
          }
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "person",
            "organization"
          ]
        },
        "names": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "CreateEntryParamsBodySourceEntityFilesItems0": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "CreatorsItems0": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "description": {
          "type": "string"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CreatorsItems0FilesItems0"
          }
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "person",
            "organization"
          ]
        },
        "names": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "CreatorsItems0FilesItems0": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "EntityFilesItems0": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "EntryCreatorsItems0": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "description": {
          "type": "string"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/EntryCreatorsItems0FilesItems0"
          }
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "person",
            "organization"
          ]
        },
        "names": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "EntryCreatorsItems0FilesItems0": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "EntryFilesItems0": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "EntrySource": {
      "type": "object",
      "properties": {
        "entity": {
          "type": "object",
          "properties": {
            "created_at": {
              "type": "string",
              "format": "dateTime"
            },
            "description": {
              "type": "string"
            },
            "files": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/EntrySourceEntityFilesItems0"
              }
            },
            "id": {
              "type": "string"
            },
            "kind": {
              "type": "string",
              "enum": [
                "person",
                "organization"
              ]
            },
            "names": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "updated_at": {
              "type": "string",
              "format": "dateTime"
            },
            "urls": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "titles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "url": {
          "type": "string"
        }
      }
    },
    "EntrySourceEntity": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "description": {
          "type": "string"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/EntrySourceEntityFilesItems0"
          }
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "person",
            "organization"
          ]
        },
        "names": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "EntrySourceEntityFilesItems0": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "FilesItems0": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "GetEntryOKBodySource": {
      "type": "object",
      "properties": {
        "entity": {
          "type": "object",
          "properties": {
            "created_at": {
              "type": "string",
              "format": "dateTime"
            },
            "description": {
              "type": "string"
            },
            "files": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetEntryOKBodySourceEntityFilesItems0"
              }
            },
            "id": {
              "type": "string"
            },
            "kind": {
              "type": "string",
              "enum": [
                "person",
                "organization"
              ]
            },
            "names": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "updated_at": {
              "type": "string",
              "format": "dateTime"
            },
            "urls": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "titles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GetEntryOKBodySourceEntity": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "description": {
          "type": "string"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GetEntryOKBodySourceEntityFilesItems0"
          }
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "person",
            "organization"
          ]
        },
        "names": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "GetEntryOKBodySourceEntityFilesItems0": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "SourceEntity": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "description": {
          "type": "string"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SourceEntityFilesItems0"
          }
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "person",
            "organization"
          ]
        },
        "names": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "SourceEntityFilesItems0": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "entity": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "description": {
          "type": "string"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/EntityFilesItems0"
          }
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "person",
            "organization"
          ]
        },
        "names": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "urls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "entry": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "creators": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/EntryCreatorsItems0"
          }
        },
        "description": {
          "type": "string"
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/EntryFilesItems0"
          }
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string",
          "enum": [
            "quote",
            "image"
          ]
        },
        "published_at": {
          "type": "string",
          "format": "dateTime"
        },
        "source": {
          "type": "object",
          "properties": {
            "entity": {
              "type": "object",
              "properties": {
                "created_at": {
                  "type": "string",
                  "format": "dateTime"
                },
                "description": {
                  "type": "string"
                },
                "files": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/EntrySourceEntityFilesItems0"
                  }
                },
                "id": {
                  "type": "string"
                },
                "kind": {
                  "type": "string",
                  "enum": [
                    "person",
                    "organization"
                  ]
                },
                "names": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "updated_at": {
                  "type": "string",
                  "format": "dateTime"
                },
                "urls": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            },
            "titles": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "url": {
              "type": "string"
            }
          }
        },
        "titles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string",
          "x-nullable": false
        }
      }
    },
    "file": {
      "type": "object",
      "properties": {
        "content_type": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "dateTime"
        },
        "filename": {
          "type": "string"
        },
        "height": {
          "type": "integer"
        },
        "path": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "dateTime"
        },
        "width": {
          "type": "integer"
        }
      }
    },
    "source": {
      "type": "object",
      "properties": {
        "entity": {
          "type": "object",
          "properties": {
            "created_at": {
              "type": "string",
              "format": "dateTime"
            },
            "description": {
              "type": "string"
            },
            "files": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SourceEntityFilesItems0"
              }
            },
            "id": {
              "type": "string"
            },
            "kind": {
              "type": "string",
              "enum": [
                "person",
                "organization"
              ]
            },
            "names": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "updated_at": {
              "type": "string",
              "format": "dateTime"
            },
            "urls": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "titles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "url": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "error": {
      "description": "error",
      "schema": {
        "type": "object",
        "required": [
          "message"
        ],
        "properties": {
          "code": {
            "type": "integer",
            "format": "int64"
          },
          "message": {
            "type": "string",
            "x-nullable": false
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "netlifyAuth": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://app.netlify.com/authorize"
    }
  },
  "security": [
    {
      "netlifyAuth": []
    }
  ]
}`))
}
